In [15]:
import numpy as np

1.Write a NumPy program to convert Fahrenheit degree to centigrade degree. Fahrenheit
values are stored in a NumPy array.

In [5]:
fahrenheit=np.array([72,64,78,67])

celsius=(fahrenheit-32)*5/9

print("Fahrenheit :", fahrenheit)
print("Celsius :", celsius)

Fahrenheit : [72 64 78 67]
Celsius : [22.22222222 17.77777778 25.55555556 19.44444444]


2.Write a NumPy program to create a random array with 1000 elements and compute the 
average, variance, standard deviation of the array elements. 

In [6]:
random_array=np.random.random(1000)

average=np.mean(random_array)
variance=np.var(random_array)
sd=np.std(random_array)

print("Average :",average)
print("Variance :",variance)
print("Standard Deviation :", sd)

Average : 0.4977998931336566
Variance : 0.08617037466698005
Standard Deviation : 0.29354790864010605


3. Write a NumPy program to convert angles from degrees to radians for all elements in a 
given array. 

In [39]:
degrees = np.array([30,45,60,90,180])

radians=np.deg2rad(degrees)

print("Degrees:", degrees)
print("Radians:", radians)

Degrees: [ 30  45  60  90 180]
Radians: [0.52359878 0.78539816 1.04719755 1.57079633 3.14159265]


4 .Write  a  NumPy  program  to  calculate  the  difference  between  neighbouring  elements, 
element-wise of a given array

In [10]:
array=np.array([23,43,12,78,89])

difference=np.diff(array)

print("Array :",array)
print("Difference :", difference)

Array : [23 43 12 78 89]
Difference : [ 20 -31  66  11]


5.Write a NumPy program to sort a given complex array using the real part first, then the 
imaginary part.

In [42]:
array = np.array([2+3j, 1+4j, 2+1j, 3+0j])

sorted_array = np.sort_complex(array)

print("Original array:", array)
print("Sorted array:", sorted_array)



Original array: [2.+3.j 1.+4.j 2.+1.j 3.+0.j]
Sorted array: [1.+4.j 2.+1.j 2.+3.j 3.+0.j]


6.Write a NumPy program to create a 1D array with random numbers and print the values 
greater than 4


In [19]:
random_array = np.random.uniform(-10, 10, 10) #(low, high, size)

values_greater_than_4 = random_array[random_array > 4]

print("Random array:", random_array)
print("Values greater than 4:", values_greater_than_4)


Random array: [-2.68115243  1.27555428 -6.11676897 -7.60955658  3.76961205 -2.33933864
  1.32566317 -1.2102311  -6.62014355 -8.94676314]
Values greater than 4: []


7. Write a NumPy program to create a 1D array with random numbers and search a particular 
number given by the user

In [37]:
random_array = np.random.randint(0, 51, 20)
print("Random array:", random_array)

num_to_search = int(input("Enter the number to search: "))

indices = np.where(random_array == num_to_search)[0]

if indices.size > 0:
    print(f"Number {num_to_search} found at indices: {indices}")
else:
    print(f"Number {num_to_search} not found in the array.")


Random array: [34 28 27 14  1 20 28  0 34 49 29 28 11 40  7 20  7 26 34 22]
Number 4 not found in the array.


8. Write a NumPy program to save a given array to a text file and load it.

In [38]:
array = np.array([1, 2, 3, 4, 5])

np.savetxt('array.txt', array, fmt='%d')

loaded_array = np.loadtxt('array.txt', dtype=int)

print("Original array:", array)
print("Loaded array:", loaded_array)


Original array: [1 2 3 4 5]
Loaded array: [1 2 3 4 5]


9.Write a NumPy program to create an array of all the even integers from 30 to 60

In [34]:
import numpy as np

even_array = np.arange(30, 61, 2)

print(even_array)


[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]


10. Write a NumPy program to compute sum of all elements ,sum of each column and sum of 
each row of a given array.

In [35]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

total_sum = np.sum(array)

column_sum = np.sum(array, axis=0)


row_sum = np.sum(array, axis=1)

print("Array:\n", array)
print("Sum of all elements:", total_sum)
print("Sum of each column:", column_sum)
print("Sum of each row:", row_sum)


Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all elements: 45
Sum of each column: [12 15 18]
Sum of each row: [ 6 15 24]
