Importing Numpy 

In [1]:
import numpy as np
p=np.array((1,2,3,4))
print(p)
print(type(p))

[1 2 3 4]
<class 'numpy.ndarray'>


Display From 0- 89

In [4]:
p=np.arange(90)
print(p)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]


Even Numbers From 2 to 200

In [5]:
p=np.arange(2,200,2)
print(p)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198]


Odd Number From 1 to 100

In [6]:
p=np.arange(1,100,2)
print(p)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


Display zeroes

In [7]:
p=np.zeros(3)
print(p)

[0. 0. 0.]


Display Ones

In [8]:
p=np.ones(4)
print(p)

[1. 1. 1. 1.]


Matrix of zeroes

In [9]:
p=np.zeros((3,3),int)
print(p)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


To Create Matrix

In [10]:
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(p)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


To Get Identity Matrix using EYE

In [11]:
p=np.eye(3)
print(p)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


To get Identity Matrix using IDENTITY

In [12]:
p=np.identity(4)
print(p)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
