Import Numpy

In [1]:
import numpy as np
a=np.arange(8)
print(a)

[0 1 2 3 4 5 6 7]


Slice Array

In [5]:
print(a[1:5])
print(a[2:5])
print(a[3:6])
print(a[1:])
print(a[:5])
print(a[3])
print(a[-4:-1])


[1 2 3 4]
[2 3 4]
[3 4 5]
[1 2 3 4 5 6 7]
[0 1 2 3 4]
3
[4 5 6]


Copy value to another variable

In [6]:
b=a
print(b)

[0 1 2 3 4 5 6 7]


To change an array element of Both Array

In [7]:
a[2]=10
print(a)
print(b)

[ 0  1 10  3  4  5  6  7]
[ 0  1 10  3  4  5  6  7]


To change only one array

In [10]:
a[3]=11
c=a.copy()
print(c)
print(b)
print(a)

[ 0  1 10 11  4  5  6  7]
[ 0  1 10 11  4  5  6  7]
[ 0  1 10 11  4  5  6  7]
