Matrix transpose and trace(Sum of daigonal elements)

In [1]:
import numpy as np

In [13]:
arr1= np.array([[1,2,3],[1,2,3],[1,2,3]])
arr2= np.array([[3,2,1],[3,2,1],[3,2,1]])
inverse=np.array([[2,1],[5,3]])

In [6]:
print(arr1)
print(arr2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[3 2 1]
 [3 2 1]
 [3 2 1]]


In [7]:
print("Transpose of first array is :")
print(np.transpose(arr1))

Transpose of first array is :
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [8]:
print("Trace of first array :")
print(np.trace(arr2))

Trace of first array :
6


In [9]:
print("Matrix Multiplication:")
print(np.dot(arr1,arr2))

Matrix Multiplication:
[[18 12  6]
 [18 12  6]
 [18 12  6]]


In [14]:
print("Inverse of the matrix :")
print(np.linalg.inv(inverse))

Inverse of the matrix :
[[ 3. -1.]
 [-5.  2.]]


In [10]:
print("Rank of the matrix :")
print(np.linalg.matrix_rank(arr1))

Rank of the matrix :
1
